"""initial schema: users, grids, months

Revision ID: 12e2594bc300
Revises: 
Create Date: 2026-07-13 20:39:31.739774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12e2594bc300'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grids',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grids_key'), 'grids', ['key'], unique=True)
    op.create_table('months',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('starting_balance', sa.Float(), nullable=False),
    sa.Column('ending_balance', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_index')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('grid_columns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('grid_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['grid_id'], ['grids.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grid_rows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('grid_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['grid_id'], ['grids.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('month_line_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('month_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.Enum('INCOME', 'FIXED', 'VARIABLE', name='lineitemcategory'), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['month_id'], ['months.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grid_cells',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('row_id', sa.String(length=36), nullable=False),
    sa.Column('column_id', sa.String(length=36), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['column_id'], ['grid_columns.id'], ),
    sa.ForeignKeyConstraint(['row_id'], ['grid_rows.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('row_id', 'column_id', name='uq_gridcell_row_column')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grid_cells')
    op.drop_table('month_line_items')
    op.drop_table('grid_rows')
    op.drop_table('grid_columns')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('months')
    op.drop_index(op.f('ix_grids_key'), table_name='grids')
    op.drop_table('grids')
    # ### end Alembic commands ###
